### ISSUE TITLE
Bug Report: Fire Pink Pixels

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#521] opened 2017-03-26 17:46 UTC
![2017-03-26_13 45 34](https://cloud.githubusercontent.com/assets/4635334/24333688/875e492e-122a-11e7-9895-0920e50e6380.png)
These pink pixels across the middle-top of the screen only appear while the fire overlay is active

**Comment by Morpheus1101** [comment] 2017-03-27 06:01
Were you wearing any armor and if so what type and mod are they from?

**Comment by MasterEric** [comment] 2017-03-27 14:37
Flux-Infused Helmet/Chest/Leggings + Slime Boots

**Comment by Morpheus1101** [comment] 2017-03-27 23:21
I tried to reproduce this in my instance but was not able to

**Comment by Aedda** [comment] 2017-03-31 23:27
Were you using a texture pack?

**Comment by Morpheus1101** [comment] 2017-04-18 23:01
Closing this issue as myself and others are unable to reproduce.

**Closed by Morpheus1101** 2017-04-18 23:01 UTC
Labels: bug, Cannot ReproDuce
