### ISSUE TITLE
Bug Report: Aroma1997's Dimensional World Portal Spawning

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#517] opened 2017-03-19 23:40 UTC
I created a portal to the mining world, inside the Deep Dark. The portal took me successfully to the mining dimension, but when I returned it took me to the overworld and spawned a portal there. In my roof.

**Comment by Morpheus1101** [comment] 2017-03-19 23:42
I will consult with the mod developer, but i strongly think that this is intended behaviour, as it would be the same thing i suspect if you did a Nether Portal from DeepDark, once you re-enterd it from nether side, itd spit you back out to overworld.

**Comment by MasterEric** [comment] 2017-03-20 00:11
In vanilla Minecraft, [Nether portals cannot be created in the End.](http://gaming.stackexchange.com/questions/47279/what-happens-when-i-create-a-nether-portal-in-the-end), so there is no real precedent. However, spawning a portal in my roof is not the best solution; what if I had machines there? Instead, Aroma's portals should either:
1. Be blocked from spawning outside the Overworld
2. Use Tile Entity data to "remember" the portal and dimension they are tied to.
I will test how the Nether Portal works.

**Comment by MasterEric** [comment] 2017-03-20 00:52
Using a Nether portal brought me to the nether, and returning brought me to a nether portal at someone else's house in the Overworld.

**Comment by Morpheus1101** [comment] 2017-03-20 03:26
So when the Nether portal went to goto Overworld, somebody else all ready an existing portal within its radius and hence linked to it, which is an ever ongoing issue with nether Portals even in Vanilla and why users are encouraged to make a netherportal form overworld and manually link it to the correct cords needed in the nether.

**Comment by Morpheus1101** [comment] 2017-03-20 03:45
https://bitbucket.org/Aroma1997/miningworld/issues/109/creating-mining-portal-from-another

**Comment by Morpheus1101** [comment] 2017-03-20 22:47
Aroma has replied via the above link saying WONTFIX

**Closed by Morpheus1101** 2017-03-20 22:47 UTC
Labels: bug
